スレッド機能の実装
kakobq/pachimon pull request #21
Opened 2021-01-13 12:05 UTC by kakobq

2021-01-15 02:34 UTC, nari requested changes
@kakobq ちょっとだけ気になった部分をコメントしてみました 👀

2021-01-15 02:34 UTC, nari commented on app/models/textboard.rb
> +  validates :description, length: { maximum: 140 }
`owner_id` はvalidatesしなくて良いですか

2021-01-15 02:34 UTC, nari commented on app/models/textboard.rb
> +  validates :title, presence: true, length: { maximum: 50 }
`title` , `description` 共に0文字でも作れちゃいそうですが、大丈夫です？

2021-01-15 02:34 UTC, nari commented on app/models/textboard_comment.rb
> +  validates :comment, presence: true, length: { maximum: 240 }
0文字でコメントできちゃいそう？

2021-01-15 02:56 UTC, kakobq commented on app/models/textboard.rb
> +  validates :description, length: { maximum: 140 }
直しました!

2021-01-15 02:57 UTC, kakobq commented on app/models/textboard.rb
> +  validates :title, presence: true, length: { maximum: 50 }
`presence: true` で0文字だとerror吐くようになってます!
descriptionはなしでも許容するようにしましたがこれも必須にしますか?

2021-01-15 02:59 UTC, kakobq commented on app/models/textboard_comment.rb
> +  validates :comment, presence: true, length: { maximum: 240 }
上記同様 `presence: true` で0文字を許容しないようになっていましたがcontrollerとviewの間でインスタンス変数での受け渡しができていなかったためフォーム上でエラーが見れないようになっていたので[修正](https://github.com/kakobq/pachimon/pull/21/commits/75cf22a8f5292e83c2477be44c3847525e868a62)しました!

2021-01-15 07:33 UTC, kakobq commented
コメント番号の実装
- コメント番号はリストを取得したときにview側で計算.
- deletedフラグを持たせてtrueだった場合コメントを差し替える.

2021-01-15 07:38 UTC, kakobq commented
最後のページの要素の数がコメントを追加するごとに変わるのでコメント番号を計算するのは割と面倒
- orderカラムをtextboard_commentsテーブルに追加
- last_comment_orderをtextboardsテーブルに追加
- deletedフラグを持たせてtrueだった場合コメントを差し替える

2021-01-15 09:12 UTC, nari commented on app/models/textboard.rb
> +  validates :title, presence: true, length: { maximum: 50 }
確🦀 `minimum` も一応指定しましょうか！

2021-01-15 09:12 UTC, nari commented on app/models/textboard_comment.rb
> +  validates :comment, presence: true, length: { maximum: 240 }
確🦀 minimum も一応指定しましょうか！

2021-01-15 09:15 UTC, nari commented
> orderカラムをtextboard_commentsテーブルに追加

`order` カラムは既に[ActiveRecordのメソッド](https://railsdoc.com/page/model_order)で存在するので、衝突しちゃいそうな気が・・・ `order_number` とかでいかがでしょうか！

> last_comment_orderをtextboardsテーブルに追加

なので、こちらも `latest_order_number` 的な・・・？

2021-01-15 13:14 UTC, kakobq commented
@nari 修正しました!

2021-01-18 04:54 UTC, nari commented on app/controllers/textboard_comments_controller.rb
> +    end
`transaction` (・∀・)ｲｲﾈ!!
このままでも良いのですが、こういう依存関係があるライフサイクル系のものは[ActiveRecordのコールバック](https://railsguides.jp/active_record_callbacks.html)のafter_createとか使用すると良いです

2021-01-18 04:56 UTC, nari approved these changes
![LGTM](https://image.lgtmoon.dev/109848)

2021-01-18 06:46 UTC, nari approved these changes
![LGTM](https://cdn.lgtmoon.dev/images/109513)

2021-01-18 06:49 UTC, merged